name: Bug report
description: File a bug report
title: "bug: <short description>"
labels: [bug]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug and steps to reproduce it.
      placeholder: Tell us what you saw.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should have happened?
  - type: input
    id: version
    attributes:
      label: Version
      placeholder: e.g., v1.0.0
